#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
    # Update icon cache
    gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
    # Update desktop database
    update-desktop-database -q || true
fi
